alias ll='ls -al --color=auto'
alias ssh-swap-config='sh /home/asandoval/Git/bash-tools/ssh-swap-config.sh'
alias ssh-swap-pfpt='ssh-swap-config PFPT'
alias ssh-swap-reg='ssh-swap-config REGULAR'
alias to-clipboard='xclip -selection clipboard'
alias goto-git-root='cd $(git rev-parse --show-toplevel)'
alias gedit='gnome-text-editor'
alias git-prune='sh /home/asandoval/Git/bash-tools/git-prune.sh'
alias git-push-regular='ssh-swap-reg && git push && ssh-swap-pfpt'
