#!/usr/bin/env python3
"""Generate the search index the web UI loads.

Walks PROJECT/MEETING/<date>.md notes under a notes-repo root and writes
<root>/.web/notes-data.js as `window.NOTES_INDEX = [...]`. Loading the index as
a plain script (rather than fetching JSON) lets the static UI work over file://
with no server. Standard library only.

The notes-repo root is taken from argv[1] (the directory `add-notes` is run in);
it defaults to the current working directory.
"""

import json
import sys
from datetime import datetime
from pathlib import Path

REPO_ROOT = Path(sys.argv[1]).resolve() if len(sys.argv) > 1 else Path.cwd()
OUTPUT = REPO_ROOT / ".web" / "notes-data.js"

# Top-level dirs that are never projects.
EXCLUDE_DIRS = {".git", ".web", "lib", "docs"}


def parse_note(path: Path):
    """Return a record dict for one note file, or None if unreadable."""
    raw = path.read_text(encoding="utf-8", errors="replace")
    project = meeting = date = None
    body = raw

    if raw.startswith("---\n"):
        end = raw.find("\n---", 4)
        if end != -1:
            front = raw[4:end]
            body = raw[end + 4:].lstrip("\n")
            for line in front.splitlines():
                if ":" not in line:
                    continue
                key, _, value = line.partition(":")
                value = value.strip().strip('"').strip("'")
                key = key.strip()
                if key == "project":
                    project = value
                elif key == "meeting":
                    meeting = value
                elif key == "date":
                    date = value

    rel = path.relative_to(REPO_ROOT)
    # Fall back to the path/filename when frontmatter is absent or partial.
    project = project or rel.parts[0]
    meeting = meeting or rel.parts[1]
    date = date or path.stem

    return {
        "project": project,
        "meeting": meeting,
        "date": date,
        "path": str(rel).replace("\\", "/"),
        "title": f"{project} / {meeting}",
        "content": body.strip(),
    }


def date_key(date: str):
    """Sortable key from a 'mmm-dd-yyyy' date; falls back to epoch on parse error."""
    try:
        return datetime.strptime(date.capitalize(), "%b-%d-%Y")
    except ValueError:
        return datetime.min


def main() -> int:
    records = []
    for path in REPO_ROOT.glob("*/*/*.md"):
        top = path.relative_to(REPO_ROOT).parts[0]
        if top in EXCLUDE_DIRS or top.startswith("."):
            continue
        records.append(parse_note(path))

    records.sort(key=lambda r: date_key(r["date"]), reverse=True)

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    payload = json.dumps(records, ensure_ascii=False, indent=2)
    OUTPUT.write_text(
        "// AUTO-GENERATED by lib/build_index.py — do not edit by hand.\n"
        f"window.NOTES_INDEX = {payload};\n",
        encoding="utf-8",
    )
    print(f"Indexed {len(records)} note(s) -> {OUTPUT.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
