#!/usr/bin/env python3
"""Generate the search index the web UI loads.

Walks notes at any depth (<dir>/.../<name>.md) under a notes-repo root and writes
<root>/.web/notes-data.js as `window.NOTES_INDEX = [...]`. Loading the index as
a plain script (rather than fetching JSON) lets the static UI work over file://
with no server. Standard library only.

The notes-repo root is taken from argv[1] (the directory `add-notes` is run in);
it defaults to the current working directory.
"""

import json
import re
import sys
from datetime import datetime
from pathlib import Path

REPO_ROOT = Path(sys.argv[1]).resolve() if len(sys.argv) > 1 else Path.cwd()
OUTPUT = REPO_ROOT / ".web" / "notes-data.js"

# Top-level dirs that are never part of the notes tree.
EXCLUDE_DIRS = {".git", ".web", "lib", "docs"}

DATE_RE = re.compile(r"^[a-z]{3}-\d{2}-\d{4}$", re.IGNORECASE)


def parse_note(path: Path):
    """Return a record dict for one note file."""
    raw = path.read_text(encoding="utf-8", errors="replace")
    date = ""
    body = raw

    if raw.startswith("---\n"):
        end = raw.find("\n---", 4)
        if end != -1:
            front = raw[4:end]
            body = raw[end + 4:].lstrip("\n")
            for line in front.splitlines():
                if ":" not in line:
                    continue
                key, _, value = line.partition(":")
                if key.strip() == "date":
                    date = value.strip().strip('"').strip("'")

    rel = path.relative_to(REPO_ROOT)
    segments = [str(p) for p in rel.parts[:-1]]  # the folder structure
    name = path.stem
    # Date: frontmatter wins; else the filename if it looks like a date.
    if not date and DATE_RE.match(name):
        date = name

    return {
        "segments": segments,
        "name": name,
        "date": date,
        "path": str(rel).replace("\\", "/"),
        "content": body.strip(),
    }


def date_key(date: str):
    """Sortable key from a 'mmm-dd-yyyy' date; falls back to epoch on parse error."""
    try:
        return datetime.strptime(date.capitalize(), "%b-%d-%Y")
    except ValueError:
        return datetime.min


def is_excluded(rel: Path) -> bool:
    """Skip notes whose path crosses an excluded or hidden directory."""
    parts = rel.parts[:-1]
    if not parts:
        return False  # a note at the repo root is allowed
    if parts[0] in EXCLUDE_DIRS:
        return True
    return any(p.startswith(".") for p in parts)


def main() -> int:
    records = []
    for path in REPO_ROOT.rglob("*.md"):
        rel = path.relative_to(REPO_ROOT)
        if is_excluded(rel):
            continue
        records.append(parse_note(path))

    records.sort(key=lambda r: (date_key(r["date"]), r["path"]), reverse=True)

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    payload = json.dumps(records, ensure_ascii=False, indent=2)
    OUTPUT.write_text(
        "// AUTO-GENERATED by lib/build_index.py — do not edit by hand.\n"
        f"window.NOTES_INDEX = {payload};\n",
        encoding="utf-8",
    )
    print(f"Indexed {len(records)} note(s) -> {OUTPUT.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
